#define IF_CLASS_HID 0x03

#define CTAPHID_PACKET_TYPE_INIT 0x80
#define CTAPHID_PACKET_TYPE_CONT 0x00

#define CTAPHID_CMD_PING        0x01
#define CTAPHID_CMD_MSG         0x03
#define CTAPHID_CMD_LOCK        0x04
#define CTAPHID_CMD_INIT        0x06
#define CTAPHID_CMD_WINK        0x08
#define CTAPHID_CMD_CBOR        0x10
#define CTAPHID_CMD_CANCEL      0x11
#define CTAPHID_CMD_KEEPALIVE   0x3B
#define CTAPHID_CMD_ERROR       0x3F

#define CTAPHID_INIT_WINK_FLAG  0x01
#define CTAPHID_INIT_CBOR_FLAG  0x04
#define CTAPHID_INIT_NMSG_FLAG  0x08
